//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uaParserResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Vendors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Vendors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uaParserResource.Vendors", typeof(Vendors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acer.
        /// </summary>
        public static string Acer {
            get {
                return ResourceManager.GetString("Acer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazon.
        /// </summary>
        public static string Amazon {
            get {
                return ResourceManager.GetString("Amazon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple.
        /// </summary>
        public static string Apple {
            get {
                return ResourceManager.GetString("Apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asus.
        /// </summary>
        public static string Asus {
            get {
                return ResourceManager.GetString("Asus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlackBerry.
        /// </summary>
        public static string BlackBerry {
            get {
                return ResourceManager.GetString("BlackBerry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTC.
        /// </summary>
        public static string HTC {
            get {
                return ResourceManager.GetString("HTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huawei.
        /// </summary>
        public static string Huawei {
            get {
                return ResourceManager.GetString("Huawei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenovo.
        /// </summary>
        public static string Lenovo {
            get {
                return ResourceManager.GetString("Lenovo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LG.
        /// </summary>
        public static string LG {
            get {
                return ResourceManager.GetString("LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meizu.
        /// </summary>
        public static string Meizu {
            get {
                return ResourceManager.GetString("Meizu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string Microsoft {
            get {
                return ResourceManager.GetString("Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorola.
        /// </summary>
        public static string Motorola {
            get {
                return ResourceManager.GetString("Motorola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia.
        /// </summary>
        public static string Nokia {
            get {
                return ResourceManager.GetString("Nokia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnePlus.
        /// </summary>
        public static string OnePlus {
            get {
                return ResourceManager.GetString("OnePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPPO.
        /// </summary>
        public static string OPPO {
            get {
                return ResourceManager.GetString("OPPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realme.
        /// </summary>
        public static string Realme {
            get {
                return ResourceManager.GetString("Realme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samsung.
        /// </summary>
        public static string Samsung {
            get {
                return ResourceManager.GetString("Samsung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sony.
        /// </summary>
        public static string Sony {
            get {
                return ResourceManager.GetString("Sony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vivo.
        /// </summary>
        public static string Vivo {
            get {
                return ResourceManager.GetString("Vivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xiaomi.
        /// </summary>
        public static string Xiaomi {
            get {
                return ResourceManager.GetString("Xiaomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZTE.
        /// </summary>
        public static string ZTE {
            get {
                return ResourceManager.GetString("ZTE", resourceCulture);
            }
        }
    }
}
