'use strict';

// Reports which regexes of the rules are exercised by the corpus.
// It walks the rules the same way rgxMapper does: the first regex that matches wins.

const { CATEGORIES, userAgents } = require('./corpus');

// Regexes that no user agent can reach, because an earlier rule always wins.
// Key: "category:pattern source".
const UNREACHABLE = {
    'device:(dell) (strea[kpr\\d ]*[\\dko])': 'an earlier device rule matches every user agent containing "dell" first',
};

function analyze(source) {
    const hits = {};
    for (const category of CATEGORIES) {
        const rules = source.regexes[category];
        hits[category] = [];
        for (let i = 0; i < rules.length; i += 2) {
            hits[category].push(rules[i].map(() => 0));
        }
    }

    for (const { ua } of userAgents()) {
        const input = source.trim(ua, source.UA_MAX_LENGTH);
        for (const category of CATEGORIES) {
            const rules = source.regexes[category];
            found: for (let i = 0; i < rules.length; i += 2) {
                for (let j = 0; j < rules[i].length; j++) {
                    if (rules[i][j].exec(input)) {
                        hits[category][i / 2][j]++;
                        break found;
                    }
                }
            }
        }
    }
    return hits;
}

function report(source, hits) {
    const lines = [
        `# Rule coverage: uaParser.Net rules ${source.RULES_VERSION}`,
        '',
        'How many corpus user agents are decided by each regex of the rules (first match wins).',
        'Generated by `tools/RuleGenerator`; do not edit.',
        '',
        '| Category | Rules | Regexes | Covered | Not covered |',
        '|---|---:|---:|---:|---:|',
    ];
    const uncovered = [];
    const unreachable = [];
    let total = 0, covered = 0;

    for (const category of CATEGORIES) {
        const counts = hits[category].flat();
        const done = counts.filter(n => n > 0).length;
        total += counts.length;
        covered += done;
        lines.push(`| ${category} | ${hits[category].length} | ${counts.length} | ${done} | ${counts.length - done} |`);

        hits[category].forEach((rule, r) => rule.forEach((n, j) => {
            if (n === 0) {
                const pattern = source.regexes[category][r * 2][j].source.replace(/\|/g, '\\|');
                const reason = UNREACHABLE[`${category}:${source.regexes[category][r * 2][j].source}`];
                if (reason) {
                    unreachable.push(`| ${category} | ${r} | ${j} | \`${pattern}\` | ${reason} |`);
                } else {
                    uncovered.push(`| ${category} | ${r} | ${j} | \`${pattern}\` |`);
                }
            }
        }));
    }
    lines.push(`| **total** | | **${total}** | **${covered}** | **${total - covered}** |`, '');

    if (uncovered.length) {
        lines.push('## Regexes no corpus user agent reaches', '', '| Category | Rule | Regex | Pattern |', '|---|---:|---:|---|', ...uncovered, '');
    }
    if (unreachable.length) {
        lines.push('## Unreachable regexes', '', 'Converted like every other rule, but no user agent can reach them.', '',
            '| Category | Rule | Regex | Pattern | Why |', '|---|---:|---:|---|---|', ...unreachable, '');
    }
    return { markdown: lines.join('\n'), total, covered, uncovered: uncovered.length };
}

module.exports = { analyze, report };
