'use strict';

// Lists every corpus user agent for which uaParser.Net's results differ from ua-parser-js 1.0.41,
// so each change to the rules is visible and deliberate (reports/differences.md).

const { CATEGORIES, userAgents } = require('./corpus');
const { FIELDS } = require('./golden');

const show = value => value === undefined || value === null ? '*none*' : `\`${String(value).replace(/\|/g, '\\|')}\``;
const cell = text => text.replace(/\|/g, '\\|');

function report(source, upstream) {
    const rows = [];
    for (const { ua } of userAgents()) {
        const ours = source.parse(ua);
        const theirs = new upstream.UAParser(ua).getResult();
        for (const category of CATEGORIES) {
            for (const field of FIELDS[category]) {
                if (ours[category][field] !== theirs[category][field]) {
                    rows.push({ category, field, ua, theirs: theirs[category][field], ours: ours[category][field] });
                }
            }
        }
    }

    const agents = new Set(rows.map(r => r.ua)).size;
    const lines = [
        `# Differences from ua-parser-js ${upstream.version}`,
        '',
        `uaParser.Net's rules (version ${source.RULES_VERSION}) began as a copy of the rules of ua-parser-js ${upstream.version}.`,
        'This report lists every corpus user agent for which the results now differ. Generated by',
        '`tools/RuleGenerator` (`npm run differences`); do not edit.',
        '',
        rows.length === 0
            ? 'No differences: the results are the same as ua-parser-js for every corpus user agent.'
            : `${rows.length} values differ, for ${agents} of ${userAgents().length} user agents.`,
        '',
    ];

    if (rows.length) {
        lines.push('| Part | Field | ua-parser-js | uaParser.Net | User agent |', '|---|---|---|---|---|');
        rows.sort((a, b) => a.category.localeCompare(b.category) || a.field.localeCompare(b.field) || a.ua.localeCompare(b.ua));
        for (const r of rows) {
            lines.push(`| ${r.category} | ${r.field} | ${show(r.theirs)} | ${show(r.ours)} | ${cell(r.ua)} |`);
        }
        lines.push('');
    }

    return { markdown: lines.join('\n'), count: rows.length, agents };
}

module.exports = { report };
