'use strict';

// Builds the example user agents for the samples and demos from corpus/extra-user-agents.txt.
// A comment line directly followed by user agents is a group heading (text before ":").

const fs = require('fs');
const path = require('path');

const SOURCE = path.join(__dirname, '..', 'corpus', 'extra-user-agents.txt');

function groups() {
    const lines = fs.readFileSync(SOURCE, 'utf8').split(/\r?\n/);
    const result = [];
    let current = null;
    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (!line.trim()) { current = null; continue; }
        if (line.trimStart().startsWith('#')) {
            const next = lines[i + 1] || '';
            if (next.trim() && !next.trimStart().startsWith('#')) {
                current = { name: line.replace(/^\s*#\s*/, '').split(':')[0].trim(), userAgents: [] };
                result.push(current);
            }
            continue;
        }
        if (current) current.userAgents.push(line);
    }
    return result;
}

function generate(csString) {
    const all = groups();
    const entries = all.flatMap(g => [`        // ${g.name}`, ...g.userAgents.map(ua => `        new(${csString(g.name)}, ${csString(ua)}),`)]);
    const code = [
        '// <auto-generated>',
        '// Generated by tools/RuleGenerator from corpus/extra-user-agents.txt. Do not edit by hand;',
        '// edit that file and run `npm run samples` in tools/RuleGenerator instead.',
        '// </auto-generated>',
        '',
        '#nullable enable',
        '',
        'using System.Collections.Generic;',
        '',
        'namespace uaParserSamples;',
        '',
        '/// <summary>Example user agents, grouped, used by the console sample and the demos.</summary>',
        'public static class SampleUserAgents',
        '{',
        '    public static IReadOnlyList<SampleUserAgent> All { get; } =',
        '    [',
        ...entries,
        '    ];',
        '}',
        '',
        'public sealed record SampleUserAgent(string Group, string UserAgent);',
        '',
    ].join('\n');
    return { code, groupCount: all.length, count: all.reduce((n, g) => n + g.userAgents.length, 0) };
}

module.exports = { generate };
