// <auto-generated>
// Generated by tools/RuleGenerator from corpus/extra-user-agents.txt. Do not edit by hand;
// edit that file and run `npm run samples` in tools/RuleGenerator instead.
// </auto-generated>

#nullable enable

using System.Collections.Generic;

namespace uaParserSamples;

/// <summary>Example user agents, grouped, used by the console sample and the demos.</summary>
public static class SampleUserAgents
{
    public static IReadOnlyList<SampleUserAgent> All { get; } =
    [
        // Desktop browsers
        new("Desktop browsers", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"),
        new("Desktop browsers", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36 Edg/140.0.0.0"),
        new("Desktop browsers", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:145.0) Gecko/20100101 Firefox/145.0"),
        new("Desktop browsers", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 OPR/123.0.0.0"),
        new("Desktop browsers", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 YaBrowser/25.8.0.0 Safari/537.36"),
        new("Desktop browsers", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Vivaldi/7.5.3735.62"),
        new("Desktop browsers", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Whale/4.32.315.22 Safari/537.36"),
        new("Desktop browsers", "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko"),
        new("Desktop browsers", "Mozilla/5.0 (Windows NT 10.0; ARM64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36 Edg/140.0.0.0"),
        new("Desktop browsers", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.0 Safari/605.1.15"),
        new("Desktop browsers", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"),
        new("Desktop browsers", "Mozilla/5.0 (Macintosh; Intel Mac OS X 14.7; rv:145.0) Gecko/20100101 Firefox/145.0"),
        new("Desktop browsers", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"),
        new("Desktop browsers", "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"),
        new("Desktop browsers", "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0"),
        new("Desktop browsers", "Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"),
        new("Desktop browsers", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) electron-app/2.4.1 Chrome/134.0.6998.205 Electron/35.7.5 Safari/537.36"),
        new("Desktop browsers", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36"),
        new("Desktop browsers", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:146.0) Gecko/20100101 Firefox/146.0"),
        new("Desktop browsers", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.1 Safari/605.1.15"),
        new("Desktop browsers", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36 OPR/124.0.0.0 (Edition std-2)"),
        new("Desktop browsers", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15 Ddg/18.6"),
        // iOS and iPadOS
        new("iOS and iPadOS", "Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Mobile/15E148 Safari/604.1"),
        new("iOS and iPadOS", "Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/139.0.7258.76 Mobile/15E148 Safari/604.1"),
        new("iOS and iPadOS", "Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/142.0 Mobile/15E148 Safari/605.1.15"),
        new("iOS and iPadOS", "Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 EdgiOS/139.0.3405.111 Mobile/15E148 Safari/605.1.15"),
        new("iOS and iPadOS", "Mozilla/5.0 (iPad; CPU OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/139.0.7258.76 Mobile/15E148 Safari/604.1"),
        new("iOS and iPadOS", "Mozilla/5.0 (iPad; CPU OS 17_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.7 Mobile/15E148 Safari/604.1"),
        new("iOS and iPadOS", "Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.0 Mobile/15E148 Safari/604.1"),
        new("iOS and iPadOS", "Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/385.0.786430453 Mobile/15E148 Safari/604.1"),
        new("iOS and iPadOS", "Mozilla/5.0 (iPad; CPU OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.1 Mobile/15E148 Safari/604.1"),
        new("iOS and iPadOS", "Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.6.1 Mobile/15E148 Safari/604.1"),
        new("iOS and iPadOS", "Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/27.0 Mobile/15E148 Safari/604.1"),
        new("iOS and iPadOS", "Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.0 EdgiOS/141.0.3537.71 Mobile/15E148 Safari/605.1.15"),
        new("iOS and iPadOS", "Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/141.0.7390.96 Mobile/15E148 Safari/604.1"),
        // Android
        new("Android", "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Mobile Safari/537.36"),
        new("Android", "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"),
        new("Android", "Mozilla/5.0 (Linux; Android 15; SM-S931B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/28.0 Chrome/130.0.0.0 Mobile Safari/537.36"),
        new("Android", "Mozilla/5.0 (Linux; Android 14; SM-X710) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/27.0 Chrome/125.0.0.0 Safari/537.36"),
        new("Android", "Mozilla/5.0 (Linux; Android 15; Pixel 9 Pro Build/AP4A.250105.002) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Mobile Safari/537.36"),
        new("Android", "Mozilla/5.0 (Linux; U; Android 14; en-us; 23127PN0CG Build/UKQ1.231003.002) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36 XiaoMi/MiuiBrowser/14.10.1-gn"),
        new("Android", "Mozilla/5.0 (Linux; Android 12; HarmonyOS; NOH-AN00; HMSCore 6.13.0.302) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.196 HuaweiBrowser/15.0.4.312 Mobile Safari/537.36"),
        new("Android", "Mozilla/5.0 (Linux; Android 14; CPH2581) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36"),
        new("Android", "Mozilla/5.0 (Linux; Android 13; RMX3630) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36"),
        new("Android", "Mozilla/5.0 (Linux; Android 14; moto g84 5G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36"),
        new("Android", "Mozilla/5.0 (Android 15; Mobile; rv:143.0) Gecko/143.0 Firefox/143.0"),
        new("Android", "Mozilla/5.0 (Linux; Android 14; SM-A546B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36 OPR/91.0.4516.82465"),
        new("Android", "Mozilla/5.0 (Linux; U; Android 13; en-US; V2250 Build/TP1A.220624.014) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.80 UCBrowser/13.8.0.1360 Mobile Safari/537.36"),
        new("Android", "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/29.0 Chrome/136.0.0.0 Mobile Safari/537.36"),
        new("Android", "Mozilla/5.0 (Linux; Android 16; Pixel 10 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Mobile Safari/537.36"),
        new("Android", "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Mobile Safari/537.36 EdgA/140.0.0.0"),
        new("Android", "Mozilla/5.0 (Linux; Android 15; 25010PN30G Build/AQ3A.240912.001) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Mobile Safari/537.36"),
        new("Android", "Mozilla/5.0 (Linux; Android 15; 24129PN74G Build/AQ3A.240912.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.135 Mobile Safari/537.36 XiaoMi/MiuiBrowser/19.2.10101-gn"),
        new("Android", "Mozilla/5.0 (Linux; Android 15; A024 Build/AP3A.240905.015.A2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36"),
        new("Android", "Mozilla/5.0 (Linux; Android 15; A142 Build/AP3A.240905.015.A2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36"),
        new("Android", "Mozilla/5.0 (Phone; OpenHarmony 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 ArkWeb/4.1.6.1 Mobile HuaweiBrowser/5.1.3.300"),
        new("Android", "Mozilla/5.0 (Tablet; OpenHarmony 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 ArkWeb/4.1.6.1 HuaweiBrowser/5.1.3.300"),
        // In-app browsers and WebViews
        new("In-app browsers and WebViews", "Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 389.0.0.29.88 (iPhone16,2; iOS 18_5; en_US; en; scale=3.00; 1290x2796; 742215231)"),
        new("In-app browsers and WebViews", "Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBAV/521.0.0.42.97;FBBV/753217408;FBDV/iPhone15,3;FBMD/iPhone;FBSN/iOS;FBSV/18.5;FBSS/3;FBCR/;FBID/phone;FBLC/en_US;FBOP/80]"),
        new("In-app browsers and WebViews", "Mozilla/5.0 (Linux; Android 14; SM-G991B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/138.0.7204.179 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/521.0.0.58.109;]"),
        new("In-app browsers and WebViews", "Mozilla/5.0 (Linux; Android 13; 2201117TG Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 XWEB/1160065 MMWEBSDK/20231202 MMWEBID/2585 MicroMessenger/8.0.47.2560(0x28002F30) WeChat/arm64 Weixin NetType/WIFI Language/en ABI/arm64"),
        new("In-app browsers and WebViews", "Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Line/14.12.0"),
        // TVs, consoles, XR and other devices
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (SMART-TV; LINUX; Tizen 8.0) AppleWebKit/537.36 (KHTML, like Gecko) 120.0.6099.5/8.0 TV Safari/537.36"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.211 Safari/537.36 WebAppManager"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (Linux; Android 12; BRAVIA 4K VH2 Build/STT1.230105.001.S12) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.230 Mobile Safari/537.36 OPR/46.0.2207.0 OMI/4.24"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (Roku/DVP-14.0 (14.0.4.5302-46)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (PlayStation; PlayStation 5/8.20) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; Xbox; Xbox Series X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edge/44.18363.8131"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (Nintendo Switch; WifiWebAuthApplet) AppleWebKit/606.4 (KHTML, like Gecko) NF/6.0.1.15.4 NintendoBrowser/5.1.0.20389"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (X11; Linux x86_64; Quest 3) AppleWebKit/537.36 (KHTML, like Gecko) OculusBrowser/38.0.0.0 SamsungBrowser/4.0 Chrome/132.0.0.0 VR Safari/537.36"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (X11; GNU/Linux) AppleWebKit/537.36 (KHTML, like Gecko) Chromium/134.0.6998.0 Chrome/134.0.6998.0 Safari/537.36 Tesla/2025.20.6-8d1d0f7e"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (Mobile; LYF/F300B/LYF-F300B-001-01-15-130718-i; Android; rv:48.0) Gecko/48.0 Firefox/48.0 KAIOS/2.5"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (X11; Linux x86_64; Quest 3S) AppleWebKit/537.36 (KHTML, like Gecko) OculusBrowser/39.1.0.0 SamsungBrowser/4.0 Chrome/134.0.0.0 VR Safari/537.36"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (Linux; Android 12; Chromecast) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.230 Safari/537.36 CrKey/1.56.500000 DeviceType/AndroidTV"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (SMART-TV; LINUX; Tizen 9.0) AppleWebKit/537.36 (KHTML, like Gecko) 130.0.6723.58/9.0 TV Safari/537.36"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (Linux; Android 12; Chromecast) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (Linux; Android 14; Google TV Streamer Build/UTTK.241011.001) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.6723.107 Safari/537.36"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (Linux; VIDAA 7.5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Hisense/2025 VIDAA/7.5"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (Linux; VIDAA 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.105 Safari/537.36 VIDAA/6.0"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (Nintendo Switch 2; WifiWebAuthApplet) AppleWebKit/609.4 (KHTML, like Gecko) NF/6.0.3.27.0 NintendoBrowser/5.1.0.32061"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (Nintendo Switch; WifiWebAuthApplet) AppleWebKit/606.4 (KHTML, like Gecko) NF/6.0.1.15.4 NintendoBrowser/5.1.0.20393"),
        new("TVs, consoles, XR and other devices", "Mozilla/5.0 (Linux; Android 14; Pixel Watch 3 Build/AW2A.250105.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.39 Mobile Safari/537.36"),
        // Bots, crawlers and tools
        new("Bots, crawlers and tools", "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.7339.80 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"),
        new("Bots, crawlers and tools", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36"),
        new("Bots, crawlers and tools", "curl/8.9.1"),
        new("Bots, crawlers and tools", "Wget/1.21.4"),
        new("Bots, crawlers and tools", "python-requests/2.32.3"),
        new("Bots, crawlers and tools", "okhttp/4.12.0"),
        new("Bots, crawlers and tools", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; GPTBot/1.2; +https://openai.com/gptbot)"),
        new("Bots, crawlers and tools", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; ClaudeBot/1.0; +claudebot@anthropic.com)"),
        new("Bots, crawlers and tools", "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"),
        // Rare devices and systems
        new("Rare devices and systems", "Mozilla/5.0 (X11; Fedora; Linux armv7hl; rv:128.0) Gecko/20100101 Firefox/128.0"),
        new("Rare devices and systems", "AppleCoreMedia/1.0.0.12B466 (iPad; U; CPU OS 8_1 like Mac OS X; en_us)"),
        new("Rare devices and systems", "Mozilla/5.0 (Linux; U; Android 3.0; en-us; Xoom Build/HRI39) AppleWebKit/534.13 (KHTML, like Gecko) Version/4.0 Safari/534.13"),
        new("Rare devices and systems", "Mozilla/5.0 (Linux; Android 7.0; LGMS210 Build/NRD90U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36"),
        new("Rare devices and systems", "Mozilla/5.0 (Linux; Android 4.0.3; KFTT Build/IML74K) AppleWebKit/537.36 (KHTML, like Gecko) Silk/3.68 like Chrome/39.0.2171.93 Safari/537.36"),
        new("Rare devices and systems", "Mozilla/5.0 (Linux; Android 5.0.2; HP Pro Slate 12 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.133 Safari/537.36"),
        new("Rare devices and systems", "Mozilla/5.0 (Linux; U; Android 2.2.1; en-us; Nook Color Build/FRG83) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1"),
        new("Rare devices and systems", "Mozilla/5.0 (Linux; Android 5.0.2; R51 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.94 Mobile Safari/537.36"),
        new("Rare devices and systems", "Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 7.11) KIN.Two 1.0"),
        new("Rare devices and systems", "Mozilla/5.0 (Linux; Android 6.0.1; MC33) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36"),
        new("Rare devices and systems", "Mozilla/5.0 (Linux; Android 11; TC26K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.92 Mobile Safari/537.36"),
        new("Rare devices and systems", "AppleCoreMedia/1.0.0.20J373 (Apple TV; U; CPU OS 16_0 like Mac OS X; en_us)"),
        new("Rare devices and systems", "Mozilla/5.0 (DTV) AppleWebKit/531.2+ (KHTML, like Gecko) Espial/6.1.5 AQUOSBrowser/2.0 (US01DTV;V;0001;0001)"),
        new("Rare devices and systems", "PebbleApp/4.4.2 (iPhone; iOS 11.4; Scale/2.00)"),
        new("Rare devices and systems", "Mozilla/5.0 (Linux; Android 7.1.1; WT6000) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Mobile Safari/537.36"),
        new("Rare devices and systems", "Mozilla/5.0 (Linux; U; Android 4.4.2; en-us; Glass 1 Build/KFS77B) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"),
        new("Rare devices and systems", "Mozilla/5.0 (X11; Mageia; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"),
        new("Rare devices and systems", "Mozilla/5.0 (X11; U; OpenSolaris i86pc; en-US; rv:1.9.0.12) Gecko/2009070611 Firefox/3.0.12"),
        new("Rare devices and systems", "Mozilla/5.0 (Linux; Android 4.2.2; SD4930UR Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Silk/3.67 like Chrome/39.0.2171.93 Mobile Safari/537.36"),
        new("Rare devices and systems", "PebbleApp/4.4.3 CFNetwork/902.2 Darwin/17.7.0"),
    ];
}

public sealed record SampleUserAgent(string Group, string UserAgent);
